% =========== for Performance Accuracy ================

A = load('Performance Accuracy.mat');
data = A.cat_mask;
UM_F = data(:,1);
M_F = data(:,4);
UM_Fa = data(:,2);
M_Fa = data(:,5);
UM_UF = data(:,3);
M_UF = data(:,6);
newdata = zeros(72,3);
newdata(:,1) = vertcat(UM_F, M_F);
newdata(:,2) = vertcat(UM_Fa, M_Fa);
newdata(:,3) = vertcat(UM_UF, M_UF);
col_mean = mean(newdata);
newdata_unmasked = newdata(1:36,:);
newdata_masked = newdata(37:72,:);
row_mean1 = mean(mean(newdata_unmasked));
row_mean2 = mean(mean(newdata_masked));
row_mean = [row_mean1 row_mean2];
stats.source = 'anova2';
%stats.sigmasq = 0.0153;
% stats.sigmasq = 0.0212;
stats.sigmasq = 0.0;
stats.colmeans = col_mean;
stats.coln = 70;
stats.rowmeans = row_mean;
stats.rown = 105;
stats.inter = 1;
stats.pval = 0.2016;
% stats.df = 68;
stats.df = 34;
%c1 = multcompare(stats)
c2 = multcompare(stats, 'Estimate', 'row')

% % ========== for reaction time ============
% A = load('Reaction Time.mat');
% data = A.cat_mask_RT;
% UM_F = data(:,1);
% M_F = data(:,4);
% UM_Fa = data(:,2);
% M_Fa = data(:,5);
% UM_UF = data(:,3);
% M_UF = data(:,6);
% newdata = zeros(70,3);
% newdata(:,1) = vertcat(UM_F, M_F);
% newdata(:,2) = vertcat(UM_Fa, M_Fa);
% newdata(:,3) = vertcat(UM_UF, M_UF);
% col_mean = mean(newdata);
% newdata_unmasked = newdata(1:35,:);
% newdata_masked = newdata(36:70,:);
% row_mean1 = mean(mean(newdata_unmasked));
% row_mean2 = mean(mean(newdata_masked));
% row_mean = [row_mean1 row_mean2];
% stats.source = 'anova2';
% stats.sigmasq = 0.0059;
% stats.colmeans = col_mean;
% stats.coln = 70;
% stats.rowmeans = row_mean;
% stats.rown = 105;
% stats.inter = 1;
% stats.pval = 0.1429;
% stats.df = 68;
% c1 = multcompare(stats)
% %c2 = multcompare(stats, 'Estimate', 'row')